# Generated by Django 5.1.4 on 2024-12-24 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='recipient',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.RemoveField(
            model_name='trainersubscriber',
            name='subscriber',
        ),
        migrations.RemoveField(
            model_name='trainersubscriber',
            name='trainer',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='TrainerSubscriber',
        ),
    ]
